---
- name: Installeer vereiste pakketten
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Maak keyrings directory aan
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Voeg Docker GPG key toe
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0444'

- name: Voeg Docker repository toe
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.sources
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: {{ ansible_facts['distribution_release'] }}
      Components: stable
      Architectures: amd64
      Signed-By: /etc/apt/keyrings/docker.asc
    mode: '0644'
  notify: restart docker

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Installeer Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  notify: restart docker

- name: Start en enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Voeg testuser toe aan docker groep
  ansible.builtin.user:
    name: testuser
    groups: docker
    append: true
